# Generated by Django 4.0.4 on 2022-05-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='phno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='phno',
            field=models.IntegerField(),
        ),
    ]
