# Generated by Django 4.0.4 on 2022-05-25 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_company_phno_alter_consumer_phno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='type',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='type',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='type',
        ),
    ]
